config_name: sfosd
E_lr: 1.0e-05
backbone: vgg19
batch_size: 10
classify_weight: 1
display_freq: 50
distill_type: roiconcat
distill_weight: 1
encoder_classify: false
encoder_feature: gap
eval_bs: 64
eval_testset1: true
eval_testset2: false
feature_dim: 512
fill_pixel: 128
gpu_id: 2
image_size: 224
local_rank: 1
max_epoch: 100
num_classes: 32
num_negative: 10
num_positive: 1
num_workers: 8
pad_pixel: 255
save_freq: 10
padding_max: 0
img_aug: false
teacher_model: teacher_sfosd.pth
teacher_path: checkpoints/teacher
test1_metrics:
- Recall@1
- Recall@5
- Recall@10
- Recall@20
test2_metrics:
- mAP
- mAP-20
- Precision@1
- Precision@5
- Precision@10
- Precision@20
test_freq: 10
triplet_margin: 0.1